# Array

In [1]:
# create array
movie_vector <- c("Akira","Toy Story","Room","The Wave","Whiplash","Star Wars","The Ring","The Artist","Jumanji")
movie_array <- array(movie_vector,dim=c(4,3))
print(movie_array)

     [,1]        [,2]         [,3]       
[1,] "Akira"     "Whiplash"   "Jumanji"  
[2,] "Toy Story" "Star Wars"  "Akira"    
[3,] "Room"      "The Ring"   "Toy Story"
[4,] "The Wave"  "The Artist" "Room"     


In [2]:
# Accessing an array
## Access an element
movie_array[1,2]
## Access row
movie_array[1,]
## Access column
movie_array[,2]

[1] "Whiplash"

[1] "Akira"    "Whiplash" "Jumanji"

[1] "Whiplash"   "Star Wars"  "The Ring"   "The Artist"

# Matrices

In [3]:
# Create an matrix
## similar in structure to an array but it has two dimentions
movie_matrix <- matrix(movie_vector,nrow=3,ncol=3)
print(movie_matrix)

     [,1]        [,2]        [,3]        
[1,] "Akira"     "The Wave"  "The Ring"  
[2,] "Toy Story" "Whiplash"  "The Artist"
[3,] "Room"      "Star Wars" "Jumanji"   


In [4]:
## Accessing an matrix
movie_matrix[2:3,1:2]

[,1]      [,2]     
[1,] Toy Story Whiplash 
[2,] Room      Star Wars

# DataFrame

In [5]:
#Create a dataframe
movies <- data.frame(name = movie_vector,
                    year = c(1995,1998,1985,2011,1936,1999,2002,1987,2024))
print(movies)

        name year
1      Akira 1995
2  Toy Story 1998
3       Room 1985
4   The Wave 2011
5   Whiplash 1936
6  Star Wars 1999
7   The Ring 2002
8 The Artist 1987
9    Jumanji 2024


In [6]:
# Acessing dataframes
## Access a column
print(movies[1])
## Access an element
print(movies[1,2])
## Access a variable
movies$name

        name
1      Akira
2  Toy Story
3       Room
4   The Wave
5   Whiplash
6  Star Wars
7   The Ring
8 The Artist
9    Jumanji
[1] 1995


[1] "Akira"      "Toy Story"  "Room"       "The Wave"   "Whiplash"  
[6] "Star Wars"  "The Ring"   "The Artist" "Jumanji"

In [7]:
# head and tail
head(movies)
tail(movies)


name      year
1 Akira     1995
2 Toy Story 1998
3 Room      1985
4 The Wave  2011
5 Whiplash  1936
6 Star Wars 1999

name       year
4 The Wave   2011
5 Whiplash   1936
6 Star Wars  1999
7 The Ring   2002
8 The Artist 1987
9 Jumanji    2024

In [8]:
# Inserting a new col
movies['length']<- c(81,125,97,199,87,139,130,119,120)
movies

name       year length
1 Akira      1995  81   
2 Toy Story  1998 125   
3 Room       1985  97   
4 The Wave   2011 199   
5 Whiplash   1936  87   
6 Star Wars  1999 139   
7 The Ring   2002 130   
8 The Artist 1987 119   
9 Jumanji    2024 120

In [9]:
# Inserting a new row
movies <-rbind(movies,c(name="Dr. StrangeLove",
                        year = 1964,length=94)
                        )
movies

name            year length
1  Akira           1995 81    
2  Toy Story       1998 125   
3  Room            1985 97    
4  The Wave        2011 199   
5  Whiplash        1936 87    
6  Star Wars       1999 139   
7  The Ring        2002 130   
8  The Artist      1987 119   
9  Jumanji         2024 120   
10 Dr. StrangeLove 1964 94

In [10]:
# Deleting rows
movies <- movies[-10,]
movies

name       year length
1 Akira      1995 81    
2 Toy Story  1998 125   
3 Room       1985 97    
4 The Wave   2011 199   
5 Whiplash   1936 87    
6 Star Wars  1999 139   
7 The Ring   2002 130   
8 The Artist 1987 119   
9 Jumanji    2024 120

In [11]:
# Deleting columns
movies["length"] <- NULL
movies

name       year
1 Akira      1995
2 Toy Story  1998
3 Room       1985
4 The Wave   2011
5 Whiplash   1936
6 Star Wars  1999
7 The Ring   2002
8 The Artist 1987
9 Jumanji    2024